location:
  name: "Home-VU24JD"

  gps:
    latitude: 11.94775
    longitude: 79.821
    altitude_m: 15

  maidenhead:
    locator: MK91VW
    precision: 6

  timezone: "Asia/Kolkata"
  coordinate_system: "WGS84"
